apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-test-app
  namespace: argocd-staging
spec:
     project: default
     source: # repositório com yaml de implantação
       repoURL: git@github.com:carina-pereira-devops/devops.git
       targetRevision: HEAD # HEAD = sempre procurar o commit principal/mais recente
       path: iac_app/prd  # pasta com o código da aplicação (pasta de acordo com o ambiente prd/dev/hml é a melhor pratica)
       directory:
         recurse: true # inclui subpastas
     destination: # cluster no qual deseja que o arquivo yaml de deploy seja implantado, neste caso no default
       server: https://kubernetes.default.svc
       namespaces: app # namespace da aplicação a ser criado de acordo com "syncOptions"
     syncPolicy:
          syncOptions:
          - CreateNamespace=true # criar namespace de destino definido se não estiver disponível
          automated: # sync a cada três minutos
            prune: true # o sync não excluirá recursos, mas para permitir que o argocd também exclua o que nós excluimos, defina prune como verdadeiro
            selfHeal: true # substituir automaticamente quaisquer alterações manuais feitas por desenvolvedores ou outras pessoas com acesso ao cluster

