apiVersion: apps/v1
kind: Deployment
metadata:
  name: python
  namespace: app
  labels:
    app: python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python
        image: 535002861869.dkr.ecr.us-east-1.amazonaws.com/dvps:20241007211927
        ports:
        - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: python-service
  namespace: app
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: python
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

